### ISSUE TITLE
Installation unter Contao 4.6.9

### ISSUE THREAD

**Issue by planepix** [trilobit-gmbh/contao-calculator-bundle#1]
Ahoi,
ich habe versucht das Bundle unter Contao 4.6.9 zu installieren - via Contao Manager - und erhlte folgende Fehlerausgabe:

$ /usr/bin/php72 '-q' '/www/htdocs/xxxxxx/web/contao-manager.phar.php' 'composer' 'require' 'trilobit-gmbh/contao-calculator-bundle' '--no-progress' '--no-suggest' '--no-update' '--no-scripts' '--prefer-stable' '--sort-packages' '--no-ansi' '--no-interaction' 2>&1

Using version ^1.1 for trilobit-gmbh/contao-calculator-bundle
/www/htdocs/xxxxxx/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

$ /usr/bin/php72 '-q' '/www/htdocs/xxxxxx/web/contao-manager.phar.php' 'composer' 'update' 'trilobit-gmbh/contao-calculator-bundle' '--with-dependencies' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' '--dry-run' 2>&1

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for trilobit-gmbh/contao-calculator-bundle ^1.1 -> satisfiable by trilobit-gmbh/contao-calculator-bundle[v1.1.0].
    - Conclusion: remove symfony/expression-language v4.1.8
    - Conclusion: don't install symfony/expression-language v4.1.8
    - trilobit-gmbh/contao-calculator-bundle v1.1.0 requires symfony/expression-language ^3.4 -> satisfiable by symfony/expression-language[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/expression-language[v3.4.0, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.1, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.10, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.11, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.12, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.13, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.14, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.15, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.16, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.17, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.18, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.19, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.2, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.3, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.4, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.5, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.6, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.7, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.8, v4.1.8].
    - Can only install one of: symfony/expression-language[v3.4.9, v4.1.8].
    - Installation request for symfony/expression-language (locked at v4.1.8) -> satisfiable by symfony/expression-language[v4.1.8].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

# Process terminated with exit code 2
# Result: Misuse of shell builtins

**Comment by trilobit-gmbh** [comment]
v1.1.1 now also allows installing symfony/expression-language in a 4.* version.
Thanks @planepix for reporting.
