### ISSUE TITLE
Make service public

### ISSUE THREAD

**Issue by m-vo** [trilobit-gmbh/contao-calculator-bundle#2]
The service `trilobit_contao_calculator.evaluator` must be public. Otherwise it will get inlined during compiliation.

**Comment by Schmidty2** [comment]
Hallo,
nach dem Update einer Seite von 4.4. auf 4.9.1 wird beim Aufruf der Seite, in der eine Rechnung bzw. Konstante eingebunden ist, ein Fehler ausgegeben.
Details in der Log-Datei: [prod-2020-03-18.log](https://github.com/trilobit-gmbh/contao-constants-bundle/files/4349078/prod-2020-03-18.log)

Verwndet wurden die Inserttags: 
{{const::name}} --> Ist bei den Konstanten definiert
{{calc::6*6}}

Der Fehler tritt auch beim Constants-Bundle auf, wenn nur eine Konstante verwendet wird.

Provider: All-Inkl Business, PHP 7.3, Contao 4.9.1, Calculator-Bundle 1.1.1, Constants-Bundle 1.0.1

**Comment by trilobit-gmbh** [comment]
Hallo Frank,ja, das ist der Fehler vgl "m-vo commented on 5 Nov 2019". Konstanten funktionieren bei mir; das calculator-Bundle muss noch hochgezogen werden. ;-(
Sorry, aber wir hängen hier gerade etwas.

**Comment by trilobit-gmbh** [comment]
done ;-)
