### ISSUE TITLE
Nutzen von Contao Inserttags

### ISSUE THREAD

**Issue by katgirl** [trilobit-gmbh/contao-calculator-bundle#4]
Wünschenswert wäre es wenn man auch die Contao-Inserttags nutzen könnte z.B. aus einem Formular heraus.

Beispiel: 
```Bitte überweisen Sie {{calc::{{post::quantity}}*19.90}} € auf folgendes Konto:```

**Comment by trilobit-gmbh** [comment]
Hallo @katgirl,

der orginal-Insert-Tag geht nicht, da hier das Caching - bzw nicht-Caching des POST - "dazwischen funkt" (analog verhält es sich mit DATE; Stichwort ESI, https://docs.contao.org/dev/framework/caching/):
Du kannst jedoch statt der {{ Klammern die [[ Klammern verwenden. Das wird in der Programmierung berücksichtigt und aufgelöst.

Dein Beispiel sieht dann wie folgt aus:
`Bitte überweisen Sie {{calc::[[post::quantity]]*19.90}} € auf folgendes Konto:`

Viele Grüße
Peter

PS.: An dieser Stelle muss die Bundle-doku ergänzt werden. Funktioniert auch mit get. ;-)

**Comment by katgirl** [comment]
Danke klappt.

**Comment by johannes-bittner** [comment]
Kann man diese Insert-Tags auch innerhalb eines Formulars nutzen, bspw. um die Summe von Feld_1 und Feld_2 in Feld_3 auszugeben: 

`{{calc::[[post::Feld_1]] + [[post::Feld_2]]}}`

... wenn ich das nämlich probiere, erhalte ich einen Fehler: 

`str_replace(): Argument #2 ($replace) must be of type array|string, null given`

... was verständlich wäre, wenn die Erweiterung das nicht bieten kann/soll.

PS: Contao 4.13, PHP 8

**Comment by trilobit-gmbh** [comment]
> Kann man diese Insert-Tags auch innerhalb eines Formulars nutzen, bspw. um die Summe von Feld_1 und Feld_2 in Feld_3 auszugeben:
> 
> `{{calc::[[post::Feld_1]] + [[post::Feld_2]]}}`
> 
> ... wenn ich das nämlich probiere, erhalte ich einen Fehler:
> 
> `str_replace(): Argument #2 ($replace) must be of type array|string, null given`
> 
> ... was verständlich wäre, wenn die Erweiterung das nicht bieten kann/soll.
> 
> PS: Contao 4.13, PHP 8

Hallo @johannes-bittner,
der Insert-Tag wird Server seitig beim Rendern des HTML aufgelöst und ausgegeben (wie alle Insert-Tags).
Wenn die beiden Werte "Feld_1" und "Feld_2" zu diesem Zeitpunkt zur Verfügung stehen (z. B. durch das abschicken eines vorherigen Formulars), dann kann der Wert berechnet werden.
Soll die (in diesem Fall) Summe jedoch beim abschicken berechnet werden (und/oder wenn "Feld_1" und "Feld_2" ausgefüllt werden), dann ist der Insert-Tag leider nicht das richtige Mittel der Wahl.
Dann müsstest Du ggf etwas Javascript bemühen (für eine Live-Berechnung) und/oder den processFormData Hook (https://docs.contao.org/dev/reference/hooks/processFormData/) um die abgeschickten Daten zu verifizieren.
Auf einer Danke-Seite würde Deine Variante funktionieren (vgl.: https://github.com/trilobit-gmbh/contao-calculator-bundle/issues/4#issuecomment-697309107).
Peter

**Comment by johannes-bittner** [comment]
Vielen Dank für die Klarstellung!
